### ISSUE TITLE
Why not use F.cosine_similarity

### ISSUE THREAD

**Issue by ruotianluo** [taoyang1122/pytorch-SimSiam#4]
Hi, I comment out using cosine_similarity by pytorch, what is the reason for that?

**Comment by taoyang1122** [comment]
No specific reasons. They should be equivalent. I tried both but just left the one which is the same as the paper.

**Comment by ruotianluo** [comment]
For some reason, I do think cosine_similarity is problematic, but I am using mixed precision.
