### ISSUE TITLE
network initialization

### ISSUE THREAD

**Issue by ruotianluo** [taoyang1122/pytorch-SimSiam#5]
Hi,

I am wondering why you added the reset_parameters.https://github.com/taoyang1122/pytorch-SimSiam/blob/main/models/simsiam.py#L83

**Comment by taoyang1122** [comment]
In the supplementary the author said they do an uniform initialization for FC and Conv layers.

**Comment by ruotianluo** [comment]
I see, didn't notice that, sorry. Thank you so much.

**Comment by ruotianluo** [comment]
Wait, I just checked the paper. The paper says they are using default pytorch initializer, so you don't need to write a customized reset_parameter.  but you do need resnet50(zero_init_residual=True)
It may affect final result.

**Comment by taoyang1122** [comment]
Yes, thanks for pointing that out.

**Comment by lynlynlyn** [comment]
Hi
I saw your discussion.  The authors say that they use default initialization of pytorch (default uniform initialization with mode='fanin'). However, the code of resnet use kaiming normal initialization with mode='fanout'. So, I think the reset_parameters is right.

Also, I would like to know what kind of initialization is used in the released model, whether zero_init  and the mixing precision are used.
